<a href="https://colab.research.google.com/github/gupta24789/Data_Science_Projects/blob/master/colab_notebooks/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensorflow 1.x

In [1]:
!pip install tensorflow-gpu==1.13.1

  Using cached https://files.pythonhosted.org/packages/7b/b1/0ad4ae02e17ddd62109cd54c291e311c4b5fd09b4d0678d3d6ce4159b0f0/tensorflow_gpu-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: tensorflow-gpu 2.0.0a0
    Uninstalling tensorflow-gpu-2.0.0a0:
      Successfully uninstalled tensorflow-gpu-2.0.0a0


In [2]:
import tensorflow as tf

tf.__version__

'1.13.1'

#### Constant

In [3]:
## Define Constant
myconst = tf.constant([[1,2],[3,4]])
myconst

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [4]:
myconst.name, myconst.shape, myconst.dtype

('Const:0', TensorShape([Dimension(2), Dimension(2)]), tf.int32)

In [5]:
## eval function can be used only with variable
myconst.eval()

ValueError: ignored

In [0]:
## You cannot access the value of const without initializing session
sess = tf.Session()

In [7]:
myval = sess.run(myconst)
myval

array([[1, 2],
       [3, 4]], dtype=int32)

#### Variable

In [8]:
myvar = tf.Variable([[1,2],[3,4]])
myvar

Instructions for updating:
Colocations handled automatically by placer.


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [9]:
myvar.name , myvar.shape, myvar.dtype

('Variable:0', TensorShape([Dimension(2), Dimension(2)]), tf.int32_ref)

In [10]:
myvar.eval()

ValueError: ignored

In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [14]:
sess.run(myvar)

array([[1, 2],
       [3, 4]], dtype=int32)

In [15]:
myvar.eval(sess)

array([[1, 2],
       [3, 4]], dtype=int32)

### Tensorflow 2.x

In [1]:
!pip install tensorflow-gpu==2.0.0-alpha0

In [14]:
import numpy as np
import tensorflow as tf

tf.__version__

'2.0.0-alpha0'

### Constant

In [3]:
myconst = tf.constant([[1,2],[3,4]])
myconst

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [4]:
myconst.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

#### Varibale

In [5]:
myvar = tf.Variable([[1,2],[3,4]])
myvar

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
myvar.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

### Operation with Tensor

In [0]:
tensor1 = tf.constant([[1,2],[3,4]])
tensor2 = tf.Variable([[1,2],[3,4]])

In [10]:
tensor1

<tf.Tensor: id=18, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
tensor2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
tensor1 * 2

<tf.Tensor: id=30, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [13]:
tensor2 + 4

<tf.Tensor: id=34, shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>

In [16]:
result = np.dot(tensor1,tensor2)

array([[<tf.Tensor: id=58, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>,
        <tf.Tensor: id=61, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>],
       [<tf.Tensor: id=64, shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>,
        <tf.Tensor: id=67, shape=(2, 2), dtype=int32, numpy=
array([[ 4,  8],
       [12, 16]], dtype=int32)>]], dtype=object)

In [17]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: id=73, shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [18]:
tf.multiply(tensor1,tensor2)

<tf.Tensor: id=76, shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

#### Strings

In [20]:
mystr = tf.Variable("saurabh")
mystr

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'saurabh'>

In [21]:
tf.strings.length(mystr)

<tf.Tensor: id=88, shape=(), dtype=int32, numpy=7>

In [23]:
tf.strings.unicode_decode(mystr, "UTF8")

<tf.Tensor: id=94, shape=(7,), dtype=int32, numpy=array([115,  97, 117, 114,  97,  98, 104], dtype=int32)>

### Storing array of strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [25]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
